name: build-and-test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.4.0

      - run: make -C app build
